services:
  - type: web
    name: barber-queue-system
    env: docker
    plan: free
    healthCheckPath: /
    envVars:
      - key: PORT
        value: 10000
      - key: DATABASE_URL
        fromDatabase:
          name: barber-db
          property: connectionString
      - key: ADMIN_IDS
        value: "[]"
      - key: NEXT_PUBLIC_API_URL
        value: ""

databases:
  - name: barber-db
    plan: free
