services:
  - type: web
    name: beauty-ladies-backend
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python run_all.py"
    plan: free
    healthCheckPath: /ping
    envVars:
      - key: PORT
        value: 10000
      - key: DATABASE_URL
        fromDatabase:
          name: beauty-ladies-db
          property: connectionString
      - key: ADMIN_IDS
        value: "[]"
      - key: NEXT_PUBLIC_API_URL
        value: ""

databases:
  - name: beauty-ladies-db
    plan: free
